# yaml-language-server: $schema=https://agentgateway.dev/schema/config
binds:
- port: 3000
  listeners:
  - routes:
      - name: gemini
        matches:
          - path:
              pathPrefix: /
            headers:
              - name: x-provider
                value:
                  exact: gemini
        backends:
          - ai:
              name: gemini
              provider:
                gemini:
                  model: gemini-2.5-flash-lite
        policies:
          cors:
            allowOrigins: ["*"]
            allowHeaders: ["*"]
          backendAuth:
            key: "$GEMINI_API_KEY"
